id: A8F13AA89
title: An Aspirational Prayer to Behold the Beautiful Face of Khecharī
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:34:15.645952
  last_modified_at: 2022-03-01 06:34:15.645961
