id: A8F13AA89
title: 'The Staircase Ascending to Khecara: A Praise in Accord with the Arrangement
  of the Realm of Holy Nāro Khecarī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:34:15.650457
  last_modified_at: 2022-03-01 06:34:15.650460
